name: Build Windows EXE

on:
  push:
    paths:
      - 'server.py'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller server.py --onefile --noconsole

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: server-exe
          path: dist/server.exe
